version: '3.8'

services:
  postService-db:
    image: mysql:8.0
    restart: always
    container_name: postService-db
    environment:
      MYSQL_DATABASE: postService_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - postService-data:/var/lib/mysql

  reviewService-db:
    image: mysql:8.0
    restart: always
    container_name: reviewService-db
    environment:
      MYSQL_DATABASE: reviewService_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - reviewService-data:/var/lib/mysql

  commentService-db:
    image: mysql:8.0
    restart: always
    container_name: commentService-db
    environment:
      MYSQL_DATABASE: commentService_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - commentService-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  postService-data:
  reviewService-data:
  commentService-data:
  rabbitmq-data:

